import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>About This Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>About This Site</h1>

        <p className={styles.description}>
          This site is an example of using Umami to manage self-hosted
          analytics.
        </p>
      </main>
    </div>
  );
}
