import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>About This Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>About This Site</h1>

        <nav style={{ marginTop: '2rem' }}>
          <Link href="/">
            <a style={{ color: 'blue', textDecoration: 'underline' }}>Home</a>
          </Link>{' '}
          <Link href="/about">
            <a style={{ color: 'blue', textDecoration: 'underline' }}>About</a>
          </Link>
        </nav>

        <p className={styles.description}>
          This site is an example of using Umami to manage self-hosted
          analytics.
        </p>
      </main>
    </div>
  );
}
