import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>This App Has Public Analytics</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>This App Has Public Analytics</h1>

        <nav style={{ marginTop: '2rem' }}>
          <Link href="/">
            <a style={{ color: 'blue', textDecoration: 'underline' }}>Home</a>
          </Link>{' '}
          <Link href="/about">
            <a style={{ color: 'blue', textDecoration: 'underline' }}>About</a>
          </Link>
        </nav>

        <p className={styles.description}>
          You can view them at{' '}
          <a
            style={{ color: 'blue', textDecoration: 'underline' }}
            href="https://umami-production-b1b7.up.railway.app/share/G9zh9XFb/Next.js%20Site"
            className="umami--click--public-analytics"
          >
            this link
          </a>
          .
        </p>
      </main>
    </div>
  );
}
